name: Build my application

on: push

jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest
    steps:
      - name: Pull our code
        uses: actions/checkout@v2
      - name: Print current directory
        run: pwd
      - name: List files in directory
        run: ls
      - name: dotnet version
        run: dotnet --version
      - name: node version
        run: node --version
      - name: npm version
        run: npm --version
      - name: Navigate to server application
        run: cd tricklink/TrickLink.Api/ && ls && pwd
      - name: Build server application
        run: dotnet build -c Release -f net5.0 -r linux-x64
      - name: Navigate to binaries
        run: cd bin/Release/net5.0/
      - name: List binaries
        run: ls
