name: Build my application

on: push

jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest
    steps:
      - name: Pull our code
        uses: actions/checkout@v2
      - name: Print current directory and list files
        run: pwd && ls
      - name: dotnet version
        run: dotnet --version
      - name: node version
        run: node --version
      - name: npm version
        run: npm --version
      - name: Build server application
        run: dotnet build -c Release
      - name: Navigate to binaries
        run: ls TrickLink.Api -R
